### ISSUE TITLE
Power consumption 用電統計的數據不正確

### ISSUE THREAD

**Issue by dragonyeh** [qqaatw/JciHitachiHA#17]
最近使用冷氣才發現用電統計與實際用電差了約5倍，目前4月的累積用電量是5.5kwh，但查詢昨天晚上10點到早上6點的用電量統計卻顯示10kwh且數值一段時間後會歸零。
去年剛新增用電量統計功能時是正常的。 謝謝！
HA版本2022.4.4
JciHitachiHA V0.3.0
![擷取-1](https://user-images.githubusercontent.com/64698316/163579760-8cd6b231-8950-4356-bb01-4d30e992af14.jpg)

**Comment by qqaatw** [comment]
See `v0.3.1`
