### ISSUE TITLE
無法新增integration

### ISSUE THREAD

**Issue by chichigoodboy** [qqaatw/JciHitachiHA#18]
在 set up a new integration的時候, 選擇hitachi smart app.
會出現這個錯誤
https://imgur.com/Ymt20BZ
想問一下可以怎麼解決嗎？
HA version:2022.3.3

**Comment by qqaatw** [comment]
名稱是 JciHitachi TW

**Comment by chichigoodboy** [comment]
直接在docker的custom_components/下把資料夾複製進去重開後就解決了👍

環境用NAS的docker架的, 路徑有點差異
 謝謝幫忙
