### ISSUE TITLE
冷氣控制錯誤

### ISSUE THREAD

**Issue by AaronFUFU** [qqaatw/JciHitachiHA#20]
<img width="646" alt="截圖 2022-06-03 上午1 25 37" src="https://user-images.githubusercontent.com/76577625/171688321-0fac97b6-502c-4ecc-8011-7009a4bb3add.png">
您好 ：

最近在使用此整合時會出現上圖之錯誤
而在控制冷氣開關和調溫度時需要過5秒以上才會有反應
冷氣型號為：RA-50QV1
透過HACS安裝

**Comment by qqaatw** [comment]
我這邊未發生此狀況。原廠APP使用是否正常？

**Comment by AaronFUFU** [comment]
Hi @qqaatw  
感謝您的回覆
原廠app的操作都正常，都是設定之後冷氣即有反應
唯有透過HA控制會有延遲，延遲時間時長時短

**Comment by qqaatw** [comment]
JciHitachiHA版本是否為最新？ 請提供HA架設環境以及網路狀況。

**Comment by AaronFUFU** [comment]
JciHitachiHA版本為最新，透過UI方式安裝，也有試過HACS安裝方式
HA安裝在Pi4 有線網路連接

**Comment by qqaatw** [comment]
如果有其他使用者也回報此問題再一併解決，目前看來是個案。

所有的操作傳遞至裝置或是狀態回傳，皆是經由日本AWS伺服器中介，跨國連線有延遲可說是正常現象。網路品質以及RPI負載狀況也有些許關係。

**Comment by TEKTEKC** [comment]
@qqaatw 大您好我這邊也有遇到相同錯誤，環境也是Pi4，HACS安裝

**Comment by qqaatw** [comment]
@TEKTEKC 該錯誤是預期中的，功能正常即不用理會。
