### ISSUE TITLE
Requirements for jcihitachi_tw not found: ['LibJciHitachi==0.5.1']

### ISSUE THREAD

**Issue by jellyman1978** [qqaatw/JciHitachiHA#21]
Hi, 
I got below error when installing the package. could you help to advice how to install LibJciHitachi under HA?

Logger: custom_components.jcihitachi_tw.config_flow
Source: custom_components/jcihitachi_tw/config_flow.py:69
Integration: jcihitachi_tw ([documentation](https://github.com/qqaatw/JciHitachiHA), [issues](https://github.com/qqaatw/JciHitachiHA/issues))
First occurred: 9:20:30 PM (1 occurrences)
Last logged: 9:20:30 PM

Failed to login API: Requirements for jcihitachi_tw not found: ['LibJciHitachi==0.5.1'].

**Comment by qqaatw** [comment]
#16
