### ISSUE TITLE
調整month_selector會讓其他冷氣的month_indicator, monthly_power_consumption變為調整的那台冷氣的數值

### ISSUE THREAD

**Issue by coolalec** [qqaatw/JciHitachiHA#22]
你好, 我發現只要調整其中一台冷氣的month_selector後, 其他台month_indicator, monthly_power_consumption數值會變成調整的那台冷氣的數值.
再麻煩幫忙確認, 謝謝.

環境: 使用Synology Docker架設
安裝方式: 使用HACS
版本: 0.3.2

複製步驟:
1. 將RAS-81NK的month_selector從0.0調整為1.0. 此時所有冷氣的month_indicator變為2022-06, monthly_power_consumption變為30.3.
![1](https://user-images.githubusercontent.com/9547520/173213596-a44d99d2-1fe0-43a7-b179-345aacc485ff.png)
2. 將RAS-40NK的month_selector從0.0調整為2.0. 此時所有冷氣的month_indicator變為2022-05, monthly_power_consumption變為17.3.
![2](https://user-images.githubusercontent.com/9547520/173213598-e1af8a11-b82c-4125-b3ab-26f9f30ee3e9.png)

**Comment by qqaatw** [comment]
Should be fixed in `v0.3.3`

**Comment by coolalec** [comment]
0.3.3版已經沒有問題了, 謝謝你超快速的修正.
