### ISSUE TITLE
Could not install 0.26 above revision

### ISSUE THREAD

**Issue by jasonlai79** [qqaatw/JciHitachiHA#23]
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 16:50:36 (1 occurrences)
Last logged: 16:50:36

Setup failed for custom integration jcihitachi_tw: Unable to import component: cannot import name 'MONTHLY_DATA' from 'custom_components.jcihitachi_tw.const' (/config/custom_components/jcihitachi_tw/const.py)

system: 2022.6.6 synology VMM Home Assistant OS

As title, the system stop on loading custom components and could not restart the system. Need replace 0.26 revision files than system can be normal.

**Comment by qqaatw** [comment]
#16

**Comment by qqaatw** [comment]
Has your issue resolved?

**Comment by qqaatw** [comment]
Have you tried removing all the old files of this integration and copying the new ones into custom component folder without using HACS?

**Comment by jasonlai79** [comment]
I've tried. The same situation.

**Comment by qqaatw** [comment]
MONTHLY_DATA was indeed removed in the latest version, this error looks like that you're partially using some old files that still import this var from const.py.

**Comment by jasonlai79** [comment]
I've tried to removed the integration setting and removed all the related files then reinstall the integration. The system could normal proceed. But when I try to setup the account, the system will auto restart after I press the "傳送" button. Roll back to 0.26 version no issue found.

**Comment by qqaatw** [comment]
Can you paste your system info like what #16 does?

**Comment by jasonlai79** [comment]
版本 | core-2022.6.7
-- | --
安裝類別 | Home Assistant OS
開發版 | false
Supervisor | true
Docker | true
使用者 | root
虛擬環境 | false
Python 版本 | 3.9.12
作業系統家族 | Linux
作業系統版本 | 5.15.45
CPU 架構 | x86_64
時區 | Asia/Taipei

**Comment by qqaatw** [comment]
Looks ok. Unless you're able to find out which causes the unexpected reboot e.g. detailed error messages, I cannot address this due to unreproducible on my side.

**Comment by qqaatw** [comment]
Feel free to reopen once you find some additional clues.
