### ISSUE TITLE
無法建立UI

### ISSUE THREAD

**Issue by EddieLee1222** [qqaatw/JciHitachiHA#24]
你好，
請問下面提到的UI 我要怎麼運行？
感謝

- Configuring via UI
Create config/custom_components folder if not existing.
Copy jcihitachi_tw into custom_components folder.
Click Configuration button on the left side of Home Assistant panel, and then click Integrations tab.
Click ADD INTEGRATION button at the bottom right corner and follow the UI.

**Comment by qqaatw** [comment]
如同字面上所述，不清楚你的問題在哪。

**Comment by EddieLee1222** [comment]
想確認這是UI怎麼執行？
因為我看不到
"Click Configuration button on the left side of Home Assistant pane"
"Click ADD INTEGRATION button at the bottom right corner and follow the UI."

**Comment by qqaatw** [comment]
這是Home Assistant的frontend 介面，若看不到請至HA論壇詢問，或是改用yaml設定。
