### ISSUE TITLE
無法成功

### ISSUE THREAD

**Issue by tiqit2** [qqaatw/JciHitachiHA#25]
請問依照您寫的方式做，無法成功，跟HA版本有關嗎?
Configuring via configuration.yaml
Create config/custom_components folder if not existing.
Copy jcihitachi_tw into custom_components folder.
Configure your email address, password, and device names, in config/configuration.yaml. If device names are not provided, they will be fetched from the API automatically. (not recommended.)
Restart Home Assistant.

**Comment by qqaatw** [comment]
「無法成功」四字沒有提供任何有效資訊辨識你的問題。

**Comment by tiqit2** [comment]
不好意思，說的不夠清楚
我有試過"Configuring via UI"與"Configuring via configuration.yaml"兩種方式，
使用"Configuring via UI"方式，Integrations tab內點ADD INTEGRATION找不到jcihitachi_tw項目
使用"Configuring via configuration.yaml"方式，重啟HA後，也沒看到jcihitachi_tw相關項目

下圖是我的HA版本等等資訊:
![image](https://user-images.githubusercontent.com/24760187/175778337-46e5e3df-6ea1-4437-9cb3-8f6460b3f58a.png)
![image](https://user-images.githubusercontent.com/24760187/175778870-fb422094-40ab-4257-b30e-f3e27fbf6a97.png)

**Comment by qqaatw** [comment]
UI:
重新整理網頁
Yaml:
請提供yaml設定檔

**Comment by tiqit2** [comment]
UI重新整理後可正常使用
另外想請問：
Month Indicator指的是什麼設定呢？

**Comment by qqaatw** [comment]
請見readme.
