### ISSUE TITLE
安裝問題

### ISSUE THREAD

**Issue by sheathier** [qqaatw/JciHitachiHA#28]
您好：
請問選擇UI之後，跑出來4行需要填寫的空格，看不到需要填寫什麼，第一二行我猜是email和密碼（hitachi app帳號的嗎？） 下面還有一個框框可以打勾，請問是安裝時哪裡設定錯誤嗎？
![截圖 2022-07-13 上午7 50 33](https://user-images.githubusercontent.com/79917467/178617284-984171b1-937e-4e08-acd8-5674fe6330bf.png)

**Comment by qqaatw** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/24835382/178755565-8aa5d47b-6a18-4464-91e5-1f574bb42530.png">
