### ISSUE TITLE
Clean filter notification not sync with app

### ISSUE THREAD

**Issue by jasonlai79** [qqaatw/JciHitachiHA#3]
型號：RD-240HH

濾網清洗推播提醒在HA打開馬上就會自動關閉，在App裡設定開啟狀態沒有跟HA裡同步

switch.xxxxx_clean_filter_notification

**Comment by qqaatw** [comment]
Hi,

謝謝回報，之前測試這個entity的確有問題。

由於日立近期通知即將進行系統轉換，包含APP以及智慧模組的系統更新，我不確定此更新會不會使整合失效，所以預計會等到轉換後確認沒問題再一併修復。

想跟你確認一下除了這個entity，其他entity操作上有遇到問題嗎?

**Comment by jasonlai79** [comment]
除了缺少的功能之外 其他的目前用起來都正常

**Comment by jasonlai79** [comment]
我想到了，希望能支援HACS，這樣插件更新能方便一點

**Comment by qqaatw** [comment]
> 我想到了，希望能支援HACS，這樣插件更新能方便一點

由於之後預計整合進HA Core，目前沒有支援HACS的規劃。

But, PR welcomed.

**Comment by delphicchen** [comment]
integration設定後一片空白，沒有裝置與實體。
不知道是不是系統更新造成

**Comment by jasonlai79** [comment]
0.2.1可以用了，感謝即時更新！
目前也還是濾網清洗推播通知沒辦法同步，其他的都正常

RD-240HH 測試能正常使用

**Comment by qqaatw** [comment]
謝謝回報。

濾網清洗推播通知會在往後更新修復，由於此功能較複雜，修復會需要一些時間。

**Comment by qqaatw** [comment]
not stale.

**Comment by qqaatw** [comment]
not stale
