### ISSUE TITLE
新增設備api login登入時出現 RuntimeError

### ISSUE THREAD

**Issue by hmj1026** [qqaatw/JciHitachiHA#31]
This error originated from a custom integration.

Logger: custom_components.jcihitachi_tw
Source: custom_components/jcihitachi_tw/__init__.py:168 
Integration: JciHitachi TW (documentation, issues) 
First occurred: September 16, 2022, 6:46:05 PM (2 occurrences) 
Last logged: 2:34:59 AM

Failed to login API: An error occurred when refreshing support code.

HA版本如下
Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by qqaatw** [comment]
Hi, I'm not going to make attempts for fixing this as this kind of works in general ineluctably falls prey to incomplete understanding of the architecture's full picture so it would likely be a waste of time in addressing this. And, notably, the cause of a runtime error is usually from the user's environment or API outages, and unlikely from the integration per se. Feel free to reopen if the problem persists every time and try to provide information as comprehensive as possible if you really want to have the issue addressed.
