### ISSUE TITLE
Assertion check error: Some of device_names are not available from the API

### ISSUE THREAD

**Issue by jellyman1978** [qqaatw/JciHitachiHA#32]
Hi,
    I have below error and can't be initialized in HA. there is no problem in my hitachi app on my smartphone (with same account/password). could you help to check?
    
Logger: custom_components.jcihitachi_tw
Source: custom_components/jcihitachi_tw/__init__.py:73
Integration: JciHitachi TW (documentation, issues)
First occurred: 1:46:48 PM (1 occurrences)
Last logged: 1:46:48 PM

**Assertion check error: Some of device_names are not available from the API.**

here are my environment.
RAS-22NJF/RAS-32NJF/RAS-81NJF

Home Assistant 2022.10.1
Supervisor 2022.09.1
Operating System 8.1

Configuring via configuration.yaml

thanks
Ken

**Comment by jellyman1978** [comment]
btw, I used latest v1.0.0 release

**Comment by qqaatw** [comment]
#26

**Comment by jellyman1978** [comment]
@qqaatw 
sorry,  bad.
it's working after correct the device name.
