### ISSUE TITLE
NotAuthorizedException

### ISSUE THREAD

**Issue by singi521** [qqaatw/JciHitachiHA#33]
An error occurred when signing into AWS Cognito Service: NotAuthorizedException Incorrect username or password.

**Comment by qqaatw** [comment]
Literally as what the message states.

**Comment by singi521** [comment]
But I have confirmed that the account and password is correct, so I also changed the password twice

error message : 2022-11-02 13:14:58.302 ERROR (Dummy-5) [JciHitachi.aws_connection] An error occurred when acquiring a new AwsCredentials: NotAuthorizedException Invalid login token. Token expired: 1667365798 >= 1667235770
