### ISSUE TITLE
But I have confirmed that the account and password is correct, so I also changed the password twice

### ISSUE THREAD

**Issue by singi521** [qqaatw/JciHitachiHA#34]
But I have confirmed that the account and password is correct, so I also changed the password twice

error message : 2022-11-02 13:14:58.302 ERROR (Dummy-5) [JciHitachi.aws_connection] An error occurred when acquiring a new AwsCredentials: NotAuthorizedException Invalid login token. Token expired: 1667365798 >= 1667235770

_Originally posted by @singi521 in https://github.com/qqaatw/JciHitachiHA/issues/33#issuecomment-1299584187_

**Comment by qqaatw** [comment]
Unfortunately there is nothing we can do here. The error message was thrown by the cloud indicating what it literally stated. I can neither confirm nor address it as my account doesn't have this issue, and I'm not an employee from Hitachi.

**Comment by singi521** [comment]
Can I turn on debug mode to confirm the complete url sent, I guess I caught the wrong account password at the beginning

**Comment by singi521** [comment]
fixed, when i update HA Core, restart and reinstall JciHitachiHA.
