### ISSUE TITLE
Unexpected target temp in fan and auto mode

### ISSUE THREAD

**Issue by stu85010** [qqaatw/JciHitachiHA#35]
## 環境
1. HA版本: `2022.11.4`
2. JciHitachiHA版本: `1.0.0` (`2326c8`)
3. 整合裝置: 日立冷暖氣 RAS-40NT
4. 裝置韌體: `6.0.037`

## 現象
1. 冷氣關機
2. 由遙控器設定為「僅送風」模式，並按遙控器上的「運轉」
3. HA控制面板的「設定溫度」會變成65535
![image](https://user-images.githubusercontent.com/5828325/205967834-e7b79320-a50b-426a-83dd-d78360d749f0.png)

4. HA控制面板的歷史紀錄也會記錄此數值，變得無法觀察目前溫度
![image](https://user-images.githubusercontent.com/5828325/205968078-328f2749-5f53-45c2-806b-ad69b0fb4f59.png)

## 期望行為
由遙控器開啟冷氣的送風模式時，JciHitachiHA不應顯示目標溫度為65535，應該保持先前從API上獲得的設定

BTW, 「自控」模式應該也不能設定溫度

**Comment by qqaatw** [comment]
Hello, do you want to file a PR against this repository? so that we could review your approach and merge. Thanks.
