### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by algovera** [qqaatw/JciHitachiHA#38]
最新版本，無法登入

Failed to login API: An error occurred when refreshing Living room support code.
2:01:21 PM – (ERROR) JciHitachi TW (custom integration) - message first occurred at 1:53:29 PM and shows up 2 times

<img width="603" alt="image" src="https://user-images.githubusercontent.com/48702353/215400305-721f6987-364d-4f38-bc6c-3cfcaa5603e0.png">

**Comment by qqaatw** [comment]
The latest system status check is passing as you can see the badge on the top of the readme. Please check your environment. #31

**Comment by dennisiver** [comment]
Now system status is changed to failing, can you fix it? THX~
