### ISSUE TITLE
Failed to login 

### ISSUE THREAD

**Issue by dennisiver** [qqaatw/JciHitachiHA#39]
System status is also failing. I still can control them through the control panel, but can’t find them from the entity list.
![CC45087C-7F2A-4ECF-B087-17A51AE35EE4](https://user-images.githubusercontent.com/108616284/218289775-633054b9-e430-4fee-9bdf-2c995b1ea399.jpeg)

**Comment by qqaatw** [comment]
The failing system status check is a FP. There is an issue with my local network that I don't have time to cope with.

Check your environment also. Prevent opening the official app when you're logging into the API.

**Comment by dennisiver** [comment]
After removed all the climate entities on the panel and logout all the official app, then restart, It works!
