### ISSUE TITLE
Incorrect username

### ISSUE THREAD

**Issue by 3FoH9l** [qqaatw/JciHitachiHA#41]
Hello, i have a trouble.

I try to setup integration. I use the same login details as in the app (airCloud Home). But i've got this massage:

_Failed to login API: An error occurred when signing into AWS Cognito Service: NotAuthorizedException Incorrect username or password._

PC with x86 cpu
Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5

**Comment by qqaatw** [comment]
Can you provide a link pointing to the app you used in App Store/Google Play?

**Comment by 3FoH9l** [comment]
Sure. App from Google Play:

https://play.google.com/store/apps/details?id=com.jch_hitachi.aircloudglobal&hl=en&gl=US&pli=1

**Comment by qqaatw** [comment]
The app for which this integration is designed is

https://play.google.com/store/apps/details?id=com.hitachi.TaiSEIA.smarthome&hl=zh_TW&gl=US

So I’m afraid that the integration does not work for you.

**Comment by 3FoH9l** [comment]
Wow. There are several applications from hitachi. It was unexpected.

Thank you for your time and good luck with the development.

**Comment by qqaatw** [comment]
Yeah indeed. Hitachi partners with local companies around the world and creates apps for the needs in those areas. So it can be confusing. The app I mentioned above is for Taiwan's Hitachi devices only.
