### ISSUE TITLE
/usr/local/lib/python3.10/site-packages/JciHitachi/aws_connection.py:520

### ISSUE THREAD

**Issue by KiryChang** [qqaatw/JciHitachiHA#42]
I have a problem as listed below,

Mqtt topic ap-northeast-1:156cf1fc-d617-4b44-aa2a-588be4b441ba/ap-northeast-1:156cf1fc-d617-4b44-aa2a-588be4b441ba_66428598536783/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"PowerConsumption":\t65535,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"CleanSwitch":\t3,\n\t"CleanNotification":\t3,\n\t"CleanStatus":\t7,\n\t"Error":\t0,\n\t"FirmwareVersion":\t"6.0.018",\n\t"FirmwareCode":\t39,\n\t"SystemTimestamp":\t80455,\n\t"RequestTimestamp":\t1680363392,\n\t"Timestamp":\t1680363392\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte

**Comment by qqaatw** [comment]
Hi, please read the contributing guideline and then modify your issue content correspondingly; otherwise, the issue will likely be neglected and closed by the stale bot.

**Comment by KiryChang** [comment]
I got it, thank you.
