### ISSUE TITLE
沒有出現開啟冷氣及調整溫度

### ISSUE THREAD

**Issue by noticeu** [qqaatw/JciHitachiHA#44]
如圖
![IMG_4328](https://user-images.githubusercontent.com/117199490/236469353-7b5619ea-0cfb-40e7-8faa-71f5f51adb70.jpeg)

**Comment by qqaatw** [comment]
Please check the contributing guide and modify your issue content accordingly.

**Comment by noticeu** [comment]
更新到1.3.1 已正常
