### ISSUE TITLE
JciHitachiMonthlyPowerConsumptionSensorEntity is using wrong state class.

### ISSUE THREAD

**Issue by RiANOl** [qqaatw/JciHitachiHA#46]
Get the warning from logs.
```
(<class 'custom_components.jcihitachi_tw.sensor.JciHitachiMonthlyPowerConsumptionSensorEntity'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total';
```
Wondering if there is suitable solution for monthly power comsumption?
Maybe it could only return the current month value to avoid month selection?

**Comment by qqaatw** [comment]
One option is to not use energy device class as the monthly power consumption is not a real-time energy measurement. We accept a PR fixing it.

> Maybe it could only return the current month value to avoid month selection?

The design for it is to let users check history power consumption, so returning the current month’s value only departs from the design.

**Comment by qqaatw** [comment]
Hey, would you mind proposing a PR fixing this? otherwise this issue will end up be closed by the stale bot.

We can try specifying `None` to the state class as the first step.

**Comment by RiANOl** [comment]
Sounds great. Let me do it.
