### ISSUE TITLE
空調溫度顯示錯誤

### ISSUE THREAD

**Issue by evan85** [qqaatw/JciHitachiHA#5]
使用機型：RAS-63NJK

已更新日立最新韌體G6.0.9
更新目前此整合最新版

![1FAE1492-4219-45E7-8ED7-D2E6619DD97B](https://user-images.githubusercontent.com/670674/149439468-63d9a7bc-1eb0-48c6-9e12-d06b3a415b02.png)

**Comment by qqaatw** [comment]
Hi, 請參閱下方comment開啟除錯模式，並在Log中找一項Thing info紀錄，查看`TemperatureSetting` 數值是否正常。

https://github.com/qqaatw/JciHitachiHA/issues/4#issuecomment-1008634167

**Comment by qqaatw** [comment]
另外你的冷氣是處於自控模式嗎？ 如果是的話顯示此數值是正常的。
