### ISSUE TITLE
May one power off device cause all device offline

### ISSUE THREAD

**Issue by jesan1212** [qqaatw/JciHitachiHA#50]
### 🐛 Describe the bug

自行安裝整合產生錯誤。

Logger: custom_components.jcihitachi_tw
Source: custom_components/jcihitachi_tw/__init__.py:165
Integration: JciHitachi TW (documentation, issues)
First occurred: 12:55:57 (1 occurrences)
Last logged: 12:55:57

Failed to login API: Timed out refreshing 書房冷氣 support code. Please ensure the device is online and avoid opening the official app.

### Environment Information

其中一台冷氣斷電後會帶出以上訊息，且所有整合內的冷氣都會顯示不可用， 打開其電源或把這台冷氣從日立APP中移除除，就可以使用了

**Comment by qqaatw** [comment]
It's expected and not a bug. You can specify which devices you would like to load during configuration.

**Comment by qqaatw** [comment]
Or, if you aren't satisfied with the current setup, i.e. one device offline causes other devices being unable to load, PRs are always welcomed, and the design is open to change if your proposal is justifiable.
