### ISSUE TITLE
one of my air conditioner shows unavaible

### ISSUE THREAD

**Issue by jellyman1978** [qqaatw/JciHitachiHA#54]
### 🐛 Describe the bug

Hi
one of my air conditioner shows unavaible, and I can control this air conditioner by my Hitachi app on my phone.
could you help to check?
![image](https://github.com/qqaatw/JciHitachiHA/assets/720580/86e6d4df-1698-4c88-8463-15bd6a437ca6)

below is error log
Logger: JciHitachi.aws_connection
Source: /usr/local/lib/python3.11/site-packages/JciHitachi/aws_connection.py:567
First occurred: August 6, 2023 at 7:04:23 AM (22 occurrences)
Last logged: 9:54:48 PM

An unknown shadow response is received. Client token: None

Logger: JciHitachi.aws_connection
Source: /usr/local/lib/python3.11/site-packages/JciHitachi/aws_connection.py:603
First occurred: August 7, 2023 at 3:25:06 AM (3 occurrences)
Last logged: 3:25:52 AM

### Environment Information

use release V1.4.0
Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4

**Comment by qqaatw** [comment]
Have you tried restarting Home Assistant?

**Comment by jellyman1978** [comment]
Hi,
yes, I tried restarting HA. and it doesn't work.

**Comment by qqaatw** [comment]
The log you paste doesn't help. Please download the full log and attach it to this issue.

**Comment by jellyman1978** [comment]
Hi 
here is full log
[home-assistant_2023-08-11T13-36-21.844Z.log.zip](https://github.com/qqaatw/JciHitachiHA/files/12321997/home-assistant_2023-08-11T13-36-21.844Z.log.zip)

**Comment by qqaatw** [comment]
Enable debug logging and then attach your log here again, please.

```
logger:
  default: info
  logs:
    custom_components.jcihitachi_tw: debug
```

**Comment by qqaatw** [comment]
It looks nothing wrong. At least the device statuses of `客廳` were correctly retrieved. 

So the problem is likely towards the home assistant itself instead of the integration.

**Comment by jellyman1978** [comment]
Hi,
thanks for checking.
and I just found there is a entity ID called 
climate.ke_ting_2. 
it works after I change the entity ID to 
climate.ke_ting_2 on dashboard.

**Comment by qqaatw** [comment]
Please keep in mind, the integration is designed to be robust as possible as we can make. We have CI and nightly system check which verifies the usability of Hitachi could every night.

If the system status badge on the readme is green, that means the last nightly check was successful, and the issue is not likely from the integration.
