### ISSUE TITLE
ha啟動時  如果除濕機沒有上電時  JciHitachiHA會開不起來

### ISSUE THREAD

**Issue by olymsix** [qqaatw/JciHitachiHA#55]
### 🐛 Describe the bug

可以改成ha啟動時  例如除濕機沒有上電時 忽略除濕機這個設備 而不要造成整個JciHitachiHA都開不起來
不知道有辦法這樣改嗎?

### Environment Information

RD-360HH
v1.4

**Comment by qqaatw** [comment]
Duplicate #50

**Comment by mustang-hsu** [comment]
同樣問題

**Comment by qqaatw** [comment]
@mustang-hsu 請參閱：#50。

您已在這邊留言數次又刪除留言。我在此明確告知，您所提到的問題近期不會處理（除非有人提出PR），這是刻意為之。

**Comment by mustang-hsu** [comment]
抱歉我看不懂如何留言，絕對不是惡意

Li-Huai (Allan) Lin ***@***.***>於 2023年12月24日 週日，下午12:57寫道：
