### ISSUE TITLE
請問devices中的name 是有規定打英文嗎?

### ISSUE THREAD

**Issue by hikevin117** [qqaatw/JciHitachiHA#56]
### 🐛 Describe the bug

首先先謝謝華人之光開發了讓大家能hacs日立冷氣, 
透過雲端智控的app ,因冷氣取名是中文的, 
我在以下的device_a_name  直接key中文好像都無法建立冷氣。
但如果以下指令都不打, 透過hacs設定, 輸入帳號密碼, 取得雲端資訊建立的就沒有問題。

但它很聰明會自己將中文字取出拼音, 例如客廳變 ke_ting.   
那我又把以下的device_name, 改成ke_ting,    但一樣不行。。。

難道使用config設定, 一定要把app的機子名稱都設定英數字才行嗎??
我有實驗過, ,確實改成英文字後, 再config輸入相關字, 就可以了.

可以說明這個部份嗎?
thank you

jcihitachi_tw:
  email: yourname@yourdomain.com
  password: password
  devices:
    - DEVICE_A_NAME
    - DEVICE_B_NAME

### Environment Information

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
JciHitachiHA版本 - 1.4

**Comment by hikevin117** [comment]
你打中文可以直接接入喔?  不是靠整合那裡輸入帳密登入的?

**Comment by qqaatw** [comment]
Just a side-project wrought on at my leisure 😄
