### ISSUE TITLE
No support for RPI-63FS

### ISSUE THREAD

**Issue by eezymurf** [qqaatw/JciHitachiHA#57]
### 🐛 Describe the bug

安裝完成輸入密碼後，家裡共11個設備出現了10個，缺的這台RPI-63FS發現目前沒支援，希望能加入支援設備清單🍻

### Environment Information

HA 2023.9.1

**Comment by qqaatw** [comment]
Shouldn't be unsupported as long as it's a regular air conditioner. 

I don't really have time to look into it in the near future, sorry. Let's keep the issue open.

**Comment by qqaatw** [comment]
You have two devices using the same name `主臥`, rename one of them so that all the devices have unique names should work.
