### ISSUE TITLE
Failed to setup 

### ISSUE THREAD

**Issue by LunarstarPony** [qqaatw/JciHitachiHA#58]
### 🐛 Describe the bug

Got this error recently after updating HA, any idea why this happened?

`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 10:08:43 PM (1 occurrences)
Last logged: 10:08:43 PM

Error setting up entry JciHitachi TW for jcihitachi_tw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 145, in async_setup_entry
    _lazy_install()
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 33, in _lazy_install
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'`

### Environment Information

Core 2023.11.1
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1
CPU Ryzen 5 3600X
JciHitachHA Version should be latest? But cound't really tell?
Have qaa single Dehumidifier (RD-360HH1)

**Comment by qqaatw** [comment]
Your JciHitachiHA version is not up to date.
