### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Parkemoon** [qqaatw/JciHitachiHA#59]
### 🐛 Describe the bug

Unable to login to Hitachi cloud. HA displays Unknown Error after entering details.

"This error originated from a custom integration.

Logger: custom_components.jcihitachi_tw.config_flow
Source: custom_components/jcihitachi_tw/config_flow.py:69
Integration: JciHitachi TW (documentation, issues)
First occurred: 23 November 2023 at 23:39:35 (9 occurrences)
Last logged: 00:10:54

Failed to login API: install_package() got an unexpected keyword argument 'find_links'"

### Environment Information

HA: 
Core
2023.11.3
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

on Raspberry Pi 4.

JciHitatchiHA v 1.5

**Comment by qqaatw** [comment]
duplicate #58

**Comment by qqaatw** [comment]
Please check the existing issues next time to prevent spamming.
