### ISSUE TITLE
Failed to login API: An error occurred when refreshing support code

### ISSUE THREAD

**Issue by z80020100** [qqaatw/JciHitachiHA#6]
您好
設定整合完成後顯示【設定失敗】
錯誤日誌如下
```
Logger: custom_components.jcihitachi_tw
Source: custom_components/jcihitachi_tw/__init__.py:157
Integration: JciHitachi TW (documentation, issues)
First occurred: 20:51:16 (3 occurrences)
Last logged: 20:59:05

Failed to login API: An error occurred when refreshing support code.
```

**Comment by qqaatw** [comment]
HI,

請參閱 Readme "Known issues" section.

**Comment by z80020100** [comment]
OK.
I will retry later by reinstalling and restarting.
Thanks a lot.

**Comment by qqaatw** [comment]
目前看來日立有稍微修改連線方式，若一直無法連線請等待新版Integration發佈。

**Comment by qqaatw** [comment]
Fixed. Please checkout the new version and see if that works.

**Comment by z80020100** [comment]
New version v0.2.1 works!
Thank you very much.
By the way, the model I tested is RA-36NV1 with module RC-W02XE.

**Comment by qqaatw** [comment]
Thanks for providing the model you tested, If you have another question, feel free to file a new issue.

Cheers!
