### ISSUE TITLE
機體顯示亮度支援

### ISSUE THREAD

**Issue by tomky** [qqaatw/JciHitachiHA#60]
Hi 想要讓冷氣能在晚上時自動把機體顯示亮度調暗或關掉，請問這個功能是有辦法支援的嗎？
雖然在官方App上可以操作，不過在HA用自動化調完溫度時設定會跑掉，變成要常常手動調整。

**Comment by qqaatw** [comment]
Basically, all the functionalities on the app are able to be implemented here. However, since the brightness control is not a must to me, I don't have plan implementing it in the near future. If you're interested in adding support of it, feel free to do so.

**Comment by tomky** [comment]
Sounds like an interesting challenge. I will check the codes and try to work on it. Likely will simulate it with an additional light device.

**Comment by mustang-hsu** [comment]
有一個問題，如果你有兩台以上的除濕機，把其中把一台的電源拔掉，然後H A重開機，jcihitachi_tw就沒有辦法登錄日立

**Comment by mustang-hsu** [comment]
有一個問題，如果你有兩台以上的除濕機，把其中把一台的電源拔掉，然後H A重開機，jcihitachi_tw就沒有辦法登錄

**Comment by qqaatw** [comment]
@mustang-hsu duplicate #55
