### ISSUE TITLE
實時用電支援（回傳功率）

### ISSUE THREAD

**Issue by luke2023** [qqaatw/JciHitachiHA#61]
請問有什麼方法能知道目前實時的功率嗎（w)謝謝

**Comment by qqaatw** [comment]
So there is a cumulative kwh sensor recording the power usage in a day. Taking the derivative of it w.r.t. time would give you a (not necessarily accurate) real-time measurement.

**Comment by luke2023** [comment]
Think you for the reply, does 精品series also have the sensor?

**Comment by qqaatw** [comment]
I've no idea about this.
