### ISSUE TITLE
登入失敗

### ISSUE THREAD

**Issue by Naanoda** [qqaatw/JciHitachiHA#63]
### 🐛 Describe the bug

帳號密碼輸入後發生以下錯誤
ERROR (SyncWorker_3) [JciHitachi.aws_connection] MQTT connection failed with exception AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.
ERROR (MainThread) [custom_components.jcihitachi_tw.config_flow] Failed to login API: An error occurred when connecting to MQTT endpoint

### Environment Information

插件安裝版本 1.5.0
系統版本
Home Assistant 2023.8.2
Supervisor 2023.12.0
Operating System 10.4
Frontend 20230802.0 - latest
rpi3-64

**Comment by argo057** [comment]
刪除後重新登入失敗.

自行安裝整合產生錯誤。

Logger: custom_components.jcihitachi_tw.config_flow
Source: custom_components/jcihitachi_tw/config_flow.py:63
Integration: JciHitachi TW (documentation, issues)
First occurred: 上午10:27:19 (4 occurrences)
Last logged: 上午10:31:27

Failed to login API: An error occurred when connecting to MQTT endpoint.

**Comment by WuAmos** [comment]
Same issue
ERROR (MainThread) [custom_components.jcihitachi_tw] Failed to login API: An error occurred when connecting to MQTT endpoint.

**Comment by harry2690** [comment]
I used Wireshark to capture the traffic, and the AWS_MQTT_ENDPOINT location did not change. The code debugging indicates a failure at the websockets_with_default_aws_signing step. I hope this information can assist you.

**Comment by bitebearpaw** [comment]
same issue


![jci](https://github.com/qqaatw/JciHitachiHA/assets/132869580/4ec86e19-fd24-43d4-9b88-3296508bb6e1)

**Comment by Johnsonhmchang** [comment]
Suddenly could not log in yesterday. Here is the log. Please help.

2023-12-29 17:58:01.063 ERROR (MainThread) [homeassistant.setup] Error during setup of component jcihitachi_tw
File "/config/custom_components/jcihitachi_tw/__init__.py", line 53, in async_setup
File "/config/custom_components/jcihitachi_tw/__init__.py", line 33, in _lazy_install

**Comment by Johnsonhmchang** [comment]
More error log information:

Logger: homeassistant.setup
Source: setup.py:332
First occurred: 下午5:58:01 (1 occurrences)
Last logged: 下午5:58:01

Error during setup of component jcihitachi_tw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 53, in async_setup
    _lazy_install()
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 33, in _lazy_install
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'

**Comment by qqaatw** [comment]
See https://github.com/qqaatw/JciHitachiHA/releases/tag/1.6.0.

**Comment by tiqit2** [comment]
![image](https://github.com/qqaatw/JciHitachiHA/assets/24760187/6f1f6aa4-aff9-48d0-9bcd-96399a35b35d)
更新到1.6.0後還是一樣使用
Home Assistant Core : 2023.11.2
