### ISSUE TITLE
設定問題

### ISSUE THREAD

**Issue by yuyi0515** [qqaatw/JciHitachiHA#64]
請問JciHitachi email要輸入甚麼?
謝謝

**Comment by Naanoda** [comment]
使用與日立app相同帳密.

**Comment by Naanoda** [comment]
目前插件有些問題無法使用 詳閱#63
三保持預設
四則建議輸入空調名稱

**Comment by qqaatw** [comment]
See https://github.com/qqaatw/JciHitachiHA/releases/tag/1.6.0.
