### ISSUE TITLE
除濕機部分sensor異常

### ISSUE THREAD

**Issue by xzero0911** [qqaatw/JciHitachiHA#68]
### 🐛 Describe the bug

更新後控制除濕機功能恢復正常
不過大部分Sensor還是異常
![螢幕擷取畫面 2023-12-31 181217](https://github.com/qqaatw/JciHitachiHA/assets/38142609/17bec97a-dda7-4f7d-a0ba-59f22f49de9d)
刪除JciHitachiHA整合再重新登入發現有問題的Sensor實體不會加入HA了
但從debug log看起來JciHitachiHA有正常抓到Sensor的值
log是擷取重新加入 請參考[這裡](https://ms1mcuedu-my.sharepoint.com/:u:/g/personal/al99360496_ms1_mcu_edu_tw/EeQuOE840dtGjN1tW8h6OcgBhConE0iSQMJT3ec4KQcTjg?e=WcOsLT)

### Environment Information

JciHitachiHA v1.6.0
RD-200HH1

**Comment by qqaatw** [comment]
Unfortunately I don't have time addressing this in the near future. This seems to me doable for contributions.

**Comment by xzero0911** [comment]
> Unfortunately I don't have time addressing this in the near future. This seems to me doable for contributions.

更新以下HA版本後問題解決了
HA Core: 2022.7.6 → 2024.1.2
HA OS: 7.6 → 8.5
