### ISSUE TITLE
Humidifier main entity cannot not be used

### ISSUE THREAD

**Issue by TWei-1101** [qqaatw/JciHitachiHA#69]
Core 2024.1.0
Supervisor 2023.12.0
Operating System 11.2
RD-200HH1
韌體：6.0.018
Integration version: v1.6.0

![1](https://github.com/qqaatw/JciHitachiHA/assets/112191764/37903b84-a910-4e83-a6a4-e19cc6c05d44)

[home-assistant_jcihitachi_tw_2024-01-05T05-18-34.301Z.log](https://github.com/qqaatw/JciHitachiHA/files/13839294/home-assistant_jcihitachi_tw_2024-01-05T05-18-34.301Z.log)

**Comment by qqaatw** [comment]
https://github.com/qqaatw/JciHitachiHA/issues/68#issuecomment-1873004654

**Comment by TWei-1101** [comment]
This issue has been resolved in the updated core version 2024.1.1.
