### ISSUE TITLE
PR#70的亮度控制是否僅能給除濕機使用？

### ISSUE THREAD

**Issue by rugal7699** [qqaatw/JciHitachiHA#71]
最近新增的PR#70的亮度控制，是否只能給除濕機使用？
重新下載了master版，冷氣的實體還是沒有新增亮度控制，
冷氣也想控制亮度不知是否哪裡需要做修改呢？感謝

**Comment by qqaatw** [comment]
You could have left a comment in the PR, and yes, it’s for dehumidifier only. cc @amigcamel

**Comment by amigcamel** [comment]
Yes, it only supports dehumidifiers for now. Light control for AC doesn't seem to be supported by [LibJciHitachi](https://github.com/qqaatw/LibJciHitachi), might need some time to dig in more.
