### ISSUE TITLE
Lost control to air conditioner

### ISSUE THREAD

**Issue by delphicchen** [qqaatw/JciHitachiHA#79]
### 🐛 Describe the bug

由1.7.0更新至1.7.1之後，喪失對冷氣的控制
控制裡面只剩下 "Month Selector"

### Environment Information

HA version: 2024.5.4
JCI version: 1.7.1
Device: RAS-36MJF、RAS-22MJF、RAS-71MJF

**Comment by qqaatw** [comment]
Can people facing similar issues comment on this?

**Comment by delphicchen** [comment]
![image](https://github.com/qqaatw/JciHitachiHA/assets/88757691/ab6fb100-e011-41ed-8d83-b61acfbd2f40)

**Comment by qqaatw** [comment]
If no one comments on this then I would say the issue is likely towards your HA setup.

**Comment by delphicchen** [comment]
> If no one comments on this then I would say the issue is likely towards your HA setup.

thanks for ur reply, I'll check my HA configuration!
