### ISSUE TITLE
請問冷氣室外機溫度一直顯示0度

### ISSUE THREAD

**Issue by dragonyeh** [qqaatw/JciHitachiHA#8]
室外機溫度實體顯示可用，但是一直都是0度，試著更新您發布的新版本，好像沒改善，可以幫忙看看嗎?謝謝!
log如下:
2022-01-18 22:33:25 DEBUG (MainThread) [custom_components.jcihitachi_tw] Thing info: [name: 主臥室
brand: HITACHI
model: RAS-50NJF
type: AC
available: True
status_code: {'DeviceType': 'AC', 'Switch': 0, 'Mode': 0, 'FanSpeed': 1, 'TemperatureSetting': 27, 'IndoorTemperature': 22, 'SleepModeRemainingTime': 0, 'VerticalWindDirectionSwitch': 0, 'HorizontalWindDirectionSetting': 3, 'MildewProof': 1, 'QuickMode': 0, 'PowerSaving': 0, 'ControlTone': 0, 'Panel': 2, 'Moisturizing': 0, 'PowerConsumption': 0, 'TaiseiaError': 0, 'FilterElapsedHour': 800, 'CleanSwitch': 0, 'CleanNotification': 0, 'CleanStatus': 0, 'Error': 0, 'RequestTimestamp': 1642516403, 'Timestamp': 1642516404, 'OutdoorTemperature': 0}
support_code: {'FirmwareId': 3, 'DeviceType': 'AC', 'Model': 'RAS-50NJF', 'FindMe': 10, 'Switch': 3, 'Mode': 31, 'FanSpeed': 31, 'TemperatureSetting': 4128, 'IndoorTemperature': 40, 'SleepModeRemainingTime': 1440, 'VerticalWindDirectionSwitch': 3, 'HorizontalWindDirectionSetting': 63, 'MildewProof': 3, 'QuickMode': 3, 'PowerSaving': 3, 'ControlTone': 3, 'Panel': 15, 'Moisturizing': 7, 'PowerConsumption': 65535, 'TaiseiaError': 85, 'FilterElapsedHour': 800, 'CleanSwitch': 3, 'CleanNotification': 3, 'CleanStatus': 7, 'Error': 0, 'FirmwareVersion': '6.0.010', 'FirmwareCode': 10, 'RequestTimestamp': 1642516402, 'Timestamp': 1642516402, 'OutdoorTemperature': 0, 'Brand': 'HITACHI'}

![image](https://user-images.githubusercontent.com/64698316/149959616-b5a7c16d-dbaf-42dd-a003-6413dcff3762.png)

**Comment by qqaatw** [comment]
請參閱Readme的支援清單，自v0.2起即不支援室外溫度。
