### ISSUE TITLE
Cannot be switch off

### ISSUE THREAD

**Issue by Johnsonhmchang** [qqaatw/JciHitachiHA#80]
### 🐛 Describe the bug

<img width="693" alt="截圖 2024-05-30 下午2 10 43" src="https://github.com/qqaatw/JciHitachiHA/assets/101802123/cd86a06f-27ce-4d11-b1b8-62d537faa66b">

the Humidifier cannot be switch off. Please refer to the error message. It said to report it to the author of the "jcihitachi_tw"

### Environment Information

Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.3
前端
20240501.1

**Comment by qqaatw** [comment]
In our bug report issue template, it clearly states "search previous issues before opening a new issue." IIRC.

**Comment by Johnsonhmchang** [comment]
Sorry, I did check with all the closed issues before I raise a new issue. I could not find a similar issue. 
In face, I did a double check on all the closed issues right now, but still could not find a similar issue.
Please help to give me a direction on rectify the problem. Many thanks.

**Comment by Johnsonhmchang** [comment]
Sorry again, after did a search, I did find a similar issue.
I will try to change the line 246 to "self.schedule_update_ha_state()", and see how it go.
Anyway, thanks a lot.

**Comment by qqaatw** [comment]
That is not the right way to fix. Why don't you even bother with just updating the integration?

**Comment by Johnsonhmchang** [comment]
I'm currently using version 1.6.0. Just check and realize that there is a new release v1.7.1
I will update my system to 1.7.1 now
Thank you very much
