### ISSUE TITLE
Incorrect email or password.

### ISSUE THREAD

**Issue by dickens0818** [qqaatw/JciHitachiHA#85]
### 🐛 Describe the bug

我的帳號密碼是正確的，
也可以在手機APP登入，
但Home Assistant整合時卻一直無法登入
顯示 Incorrect email or password.

### Environment Information

JciHitachiHA Release v1.8.0
Home Assistant最新版

**Comment by qqaatw** [comment]
make sure all the devices under your account are online.

**Comment by ChunYiLiao** [comment]
我之前也發生相同問題卡住一陣子，後來發現APP如果有出現凍結洗淨的提示，先執行凍結洗淨讓提示消失，這樣就正常了。

**Comment by qqaatw** [comment]
Closing due to no further activity.

**Comment by Tony427** [comment]
所以是什麼原因，導致需要凍結洗淨的時候，無法登入呢? 真的很怪...明明這時候app是可以登入的，但HA卻失效
