### ISSUE TITLE
Failure to login.

### ISSUE THREAD

**Issue by nebulaforest** [qqaatw/JciHitachiHA#87]
### 🐛 Describe the bug

Cannot login with JciHitachiHA since last week. Following is the error log. Cannot figure out what happen. 
All the devices are online in my app.

記錄器: JciHitachi.aws_connection
來源: /usr/local/lib/python3.12/site-packages/JciHitachi/aws_connection.py:579
首次發生: 上午11:53:30 (19 事件)
最後紀錄: 下午4:37:10

Mqtt topic ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb/ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb_66428598611012/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006\\u0001R",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"ScheduleOn":\t1440,\n\t"ScheduleOff":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"Checksum":\t246,\n\t"Error":\t0,\n\t"WiFiSSID":\t"nebula-UniFi-IOT",\n\t"FirmwareVersion":\t"6.0.023",\n\t"FirmwareCode":\t44,\n\t"SystemTimestamp":\t16780,\n\t"RequestTimestamp":\t1723002937,\n\t"Timestamp":\t1723002937\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte
Mqtt topic ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb/ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb_66428598611012/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006\\u0001R",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"ScheduleOn":\t1440,\n\t"ScheduleOff":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"Checksum":\t246,\n\t"Error":\t0,\n\t"WiFiSSID":\t"nebula-UniFi-IOT",\n\t"FirmwareVersion":\t"6.0.023",\n\t"FirmwareCode":\t44,\n\t"SystemTimestamp":\t17456,\n\t"RequestTimestamp":\t1723003612,\n\t"Timestamp":\t1723003612\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte
Mqtt topic ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb/ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb_66428598611012/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006\\u0001R",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"ScheduleOn":\t1440,\n\t"ScheduleOff":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"Checksum":\t246,\n\t"Error":\t0,\n\t"WiFiSSID":\t"nebula-UniFi-IOT",\n\t"FirmwareVersion":\t"6.0.023",\n\t"FirmwareCode":\t44,\n\t"SystemTimestamp":\t17661,\n\t"RequestTimestamp":\t1723003818,\n\t"Timestamp":\t1723003818\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte
Mqtt topic ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb/ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb_66428598611012/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006\\u0001R",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"ScheduleOn":\t1440,\n\t"ScheduleOff":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"Checksum":\t246,\n\t"Error":\t0,\n\t"WiFiSSID":\t"nebula-UniFi-IOT",\n\t"FirmwareVersion":\t"6.0.023",\n\t"FirmwareCode":\t44,\n\t"SystemTimestamp":\t33435,\n\t"RequestTimestamp":\t1723019591,\n\t"Timestamp":\t1723019592\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte
Mqtt topic ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb/ap-northeast-1:ddf33838-da1e-4c5a-b121-14dd6d30a3eb_66428598611012/registration/response published with payload b'{\n\t"FirmwareId":\t3,\n\t"DeviceType":\t1,\n\t"Model":\t"RAD-\xff\\u0006\\u0001R",\n\t"FindMe":\t10,\n\t"Switch":\t3,\n\t"Mode":\t31,\n\t"FanSpeed":\t31,\n\t"TemperatureSetting":\t4128,\n\t"IndoorTemperature":\t40,\n\t"SleepModeRemainingTime":\t1440,\n\t"ScheduleOn":\t1440,\n\t"ScheduleOff":\t1440,\n\t"MildewProof":\t3,\n\t"QuickMode":\t3,\n\t"PowerSaving":\t3,\n\t"ControlTone":\t3,\n\t"TaiseiaError":\t85,\n\t"FilterElapsedHour":\t800,\n\t"Checksum":\t246,\n\t"Error":\t0,\n\t"WiFiSSID":\t"nebula-UniFi-IOT",\n\t"FirmwareVersion":\t"6.0.023",\n\t"FirmwareCode":\t44,\n\t"SystemTimestamp":\t33672,\n\t"RequestTimestamp":\t1723019828,\n\t"Timestamp":\t1723019829\n}' cannot be decoded: 'utf-8' codec can't decode byte 0xff in position 53: invalid start byte

記錄器: JciHitachi.aws_connection
來源: /usr/local/lib/python3.12/site-packages/JciHitachi/aws_connection.py:631
首次發生: 上午11:55:47 (90 事件)
最後紀錄: 下午4:37:20

An unknown shadow response is received. Client token: 66428598662299
An unknown shadow response is received. Client token: 66428598655214
An unknown shadow response is received. Client token: 66428598611006
An unknown shadow response is received. Client token: 66428598610989
An unknown shadow response is received. Client token: 66428598662127

自行安裝整合產生錯誤。

記錄器: custom_components.jcihitachi_tw.config_flow
來源: custom_components/jcihitachi_tw/config_flow.py:63
整合: JciHitachi TW (相關文件, 問題)
首次發生: 上午11:53:42 (5 事件)
最後紀錄: 下午4:37:22

Failed to login API: An event occurred but wasn't accompanied with data when refreshing 客臥空調 support code.

### Environment Information

HA version: 
Core 2024.7.4
Supervisor 2024.08.0
Operating System 12.4
前端 20240710.0
JciHitachiHA version: 1.8.0

**Comment by qqaatw** [comment]
Feel free to debug and file a PR here if you're comfortable with programming.

**Comment by nebulaforest** [comment]
It ended result successful login after rebooting all Hitachi cloud module, despite all devices showed online in app.
