### ISSUE TITLE
set climate fail

### ISSUE THREAD

**Issue by pwh811213** [qqaatw/JciHitachiHA#88]
### 🐛 Describe the bug

<img width="1081" alt="截圖 2024-09-01 上午9 54 26" src="https://github.com/user-attachments/assets/94a4b6b9-75de-4e73-bbfe-28c6c4bd7b2c">

This issue has been bothering me for a while. The plugin isn't working right now, and I can't figure out what's gone wrong, but it was working fine before.

### Environment Information

HA version:2024.8.3
JciHitachiHA version:1.8.0

**Comment by hikevin117** [comment]
一樣的問題, 不能使用中.

**Comment by qqaatw** [comment]
I just triggered the system status test, it worked as usual - https://github.com/qqaatw/LibJciHitachi/actions/runs/10674185910/job/29584266870.

Did you update Home Assistant Core lately?

**Comment by pwh811213** [comment]
yes, I just update my home assistant core

**Comment by qqaatw** [comment]
Can you upload your log file here?  Feel free to redact personal information before doing so.

**Comment by hikevin117** [comment]
I have two machines. On one machine, I solved the problem by removing the xiaomi_cloud_map_extractor. On the other machine, I solved it by upgrading the Home Assistant Core.
thank you

**Comment by pwh811213** [comment]
[home-assistant_2024-09-05T12-26-01.634Z.log](https://github.com/user-attachments/files/16893373/home-assistant_2024-09-05T12-26-01.634Z.log)

**Comment by qqaatw** [comment]
Unfortunately I may not have time diving into it in the near future. If anyone used to have this issue and has resolved it please help @pwh811213 debug.
