### ISSUE TITLE
Failure to setup whenever updated to new version of HA

### ISSUE THREAD

**Issue by wingmare** [qqaatw/JciHitachiHA#94]
### 🐛 Describe the bug

2 types of error

記錄器: homeassistant.util.package
來源: util/package.py:152
首次發生: 下午6:14:31 (1 事件)
最後紀錄: 下午6:14:31

Unable to install package LibJciHitachi==1.6.0: error: Failed to fetch: `https://wheels.home-assistant.io/musllinux-index/libjcihitachi/` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://wheels.home-assistant.io/musllinux-index/libjcihitachi/) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Try again Caused by: failed to lookup address information: Try again

-----------------
記錄器: homeassistant.setup
來源: setup.py:269
首次發生: 下午6:19:16 (1 事件)
最後紀錄: 下午6:19:16

Setup failed for custom integration 'jcihitachi_tw': Requirements for jcihitachi_tw not found: ['LibJciHitachi==1.6.0'].

### Environment Information

HA 2024.10.x -2024.12.X

**Comment by qqaatw** [comment]
This's weird as it shouldn't have looked up the musllinux index the from the home assistant wheel house. What's your hardware and home assistant installation type? can you paste a screenshot of your ha system info here?

**Comment by wingmare** [comment]
Restarting HA solves the problem.
This happens when HA updates to new version.

版本	core-2024.12.5
安裝類型	Home Assistant Container
開發版	false
Supervisor	false
Docker	true
使用者	root
虛擬環境	false
Python 版本	3.13.0
作業系統家族	Linux
作業系統版本	4.4.302+
CPU 架構	x86_64
時區	Asia/Taipei
設定目錄	/config
Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
HACS Data	ok
GitHub API Calls Remaining	5000
Installed Version	2.0.1
Stage	running
Available Repositories	1496
Downloaded Repositories	24
